# Generated by Django 4.2.4 on 2023-09-07 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
