# Generated by Django 4.2.4 on 2023-09-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='balance',
            field=models.FloatField(blank=True, default=0, max_length=255),
        ),
    ]
